language: python

cache: pip

python:
    - "3.5"
    - "3.5-dev"
    - "3.6"
    - "3.6-dev"
    - "3.7-dev"
    - "nightly"

env:
    - DJANGO_VERSION=1.8.17
    - DJANGO_VERSION=1.9.12
    - DJANGO_VERSION=1.10.6


install:
    - pip install -q Django==$DJANGO_VERSION
    - pip install coveralls
    - pip install codecov
    - cp monkey_pdns/settings.example.py monkey_pdns/settings.py
    - python manage.py migrate

script: 
    - coverage run --source="." manage.py test

after_success:
    - coveralls
    - codecov

addons:
    code_climate:
        repo_token: 45e76e2a699f55c0ad633545d9588f0348e29bc55ab4c35a1075214f7f707198

